modLoader="javafml"
loaderVersion="[37,)"
license="MIT"
issueTrackerURL="https://github.com/Leximon/Fluidlogged/issues"

[[mods]]
    modId="fluidlogged"
    version="${file.jarVersion}"
    displayName="Fluidlogged"
    description="Allows waterlogging with any fluid"
    authors="Leximon"
    credits="MoreThanHidden"
    logoFile="assets/fluidlogged/icon.png"
    displayURL="https://github.com/Leximon/Fluidlogged"

[[dependencies.fluidlogged]]
    modId="forge"
    mandatory=true
    versionRange="[44,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.fluidlogged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.3,]"
    ordering="NONE"
    side="BOTH"